name: apps-setup
on: push

jobs:
  apps-setup:
    name: Test Apps.Installer.ps1 
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Applications - Apps.Installer.ps1
        run: |       
          $env:CI_WINDOWS=$true
          ./src/lib/Apps.Installer.ps1 

      - name: Test Apps.Installer.Tests.ps1 file
        shell: pwsh
        run: |       
          $env:CI_WINDOWS=$true
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine
          Invoke-Pester src\lib\Apps.Installer.Tests.ps1 -Output Detailed
