name: apps-setup

on:
  push:
    branches: 
      - main
    paths:
      - 'src/lib/common.ps1'
      - 'src/lib/log.ps1'
      - 'src/lib/Apps.Installer.ps1'
      - 'src/lib/Apps.Installer.Tests.ps1'
      - '.github/workflows/apps.yml'

jobs:
  apps-setup:
    name: Test Apps.Installer.ps1 
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Init Test Suite
        uses: potatoqualitee/psmodulecache@v4
        with:
          modules-to-cache: Pester
          shell: pwsh

      - name: Install Pre-Requisites Windows - (Not to be done in Desktop)
        shell: pwsh
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          Join-Path (Resolve-Path ~).Path "scoop\shims" >> $Env:GITHUB_PATH

      - name: Test Apps.Installer.Tests.ps1 file
        shell: pwsh
        run: |       
          $env:CI_WINDOWS=$true
          Invoke-Pester src\lib\Apps.Installer.Tests.ps1 -Output Detailed
