name: apps-setup
on: push

jobs:
  apps-setup:
    name: Test Apps.Installer.ps1 
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Init Test Suite
        uses: potatoqualitee/psmodulecache@v4
        with:
          modules-to-cache: Pester
          shell: powershell

      - name: Install Scoop
        shell: powershell
        run: |       
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')

      # - name: Test Apps.Installer.Tests.ps1 file
      #   shell: powershell
      #   run: |       
      #     $env:CI_WINDOWS=$true
      #     Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine
      #     Invoke-Pester src\lib\Apps.Installer.Tests.ps1 -Output Detailed
