name: e2e
on: push

jobs:
  e2e:
    name: Test e2e.Tests.ps1 
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Init Test Suite
        uses: potatoqualitee/psmodulecache@v4
        with:
          modules-to-cache: Pester
          shell: pwsh

      - name: Install Pre-Requisites Windows - (Not to be done in Desktop)
        shell: pwsh
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          Join-Path (Resolve-Path ~).Path "scoop\shims" >> $Env:GITHUB_PATH

      - name: Test e2e.Tests.ps1 file
        shell: pwsh
        run: |       
          $env:CI_WINDOWS=$true
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine
          Invoke-Pester e2e.Tests.ps1 -Tag "prerequisite"  -Output Detailed
          Invoke-Pester e2e.Tests.ps1 -Tag "apps" -Output Detailed
