# This is a basic workflow to help you get started with Actions

name: hyperv

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Run Workspace setup
      - name: Run workspace setup - first time
        shell: pwsh
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine
          iwr -useb https://git.io/JZBfh | iex

      # Run Workspace setup
      - name: Run workspace setup - second time
        shell: pwsh
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine
          iwr -useb https://git.io/JZBfh | iex

      - name: Run Test 
        run: | 
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine
          Invoke-Pester e2e.Tests.ps1 -Output Detailed



