name: hyperv-setup
on: push

jobs:
  hyperv-setup:
    name: Test HyperV.ps1 
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Init Test Suite
        uses: potatoqualitee/psmodulecache@v4
        with:
          modules-to-cache: Pester
          shell: powershell

      - name: Test HyperV.Tests.ps1 file
        shell: powershell
        run: |       
          Invoke-Pester src\lib\HyperV.Tests.ps1 -Output Detailed 
