name: Windows System Tests via Pester
on: push

jobs:
  pester-test:
    name: Pester Test
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install PSScriptAnalyzer module
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -ErrorAction Stop
      - name: Lint with PSScriptAnalyzer
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path *.ps1 -Recurse -Outvariable issues
          $errors   = $issues.Where({$_.Severity -eq 'Error'})
          $warnings = $issues.Where({$_.Severity -eq 'Warning'})
          if ($errors) {
              Write-Error "There were $($errors.Count) errors and $($warnings.Count) warnings total." -ErrorAction Stop
          } else {
              Write-Output "There were $($errors.Count) errors and $($warnings.Count) warnings total."
          }
      - name: Perform a Pester test from the command-line
        shell: pwsh
        run: Test-Path "C:\Windows" | Should -Be $true
      - name: Perform Windows System Tests from System.Tests.ps1 file
        shell: pwsh
        run: |
          Invoke-Pester src\lib\system.Tests.ps1 -Output Detailed
