name: workspace-setup
on: push

jobs:
  workspace-setup:
    name: Test Workspace Setup script - Workspace.ps1
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Init Test Suite
        uses: potatoqualitee/psmodulecache@v4
        with:
          modules-to-cache: Pester
          shell: powershell

      - name: Perform Workspace setup Tests from Workspace.Tests.ps1 file
        shell: powershell
        run: |       
          Invoke-Pester src\lib\Workspace.Tests.ps1 -Output Detailed

